import React from "react";

export default React.createContext({
  ingredients: [
    { value: "apples", label: "Apples", checked: false },
    { value: "avocado", label: "Avocado", checked: false },
    { value: "bacon", label: "Bacon", checked: false },
    { value: "bread", label: "Bread", checked: false },
    { value: "broccoli", label: "Broccoli", checked: false },
    { value: "butter", label: "Butter", checked: false },
    { value: "cauliflower", label: "Cauliflower", checked: false },
    { value: "cheese", label: "Cheese", checked: false },
    { value: "chicken", label: "Chicken", checked: false },
    { value: "cream cheese", label: "Cream Cheese", checked: false },
    { value: "eggs", label: "Eggs", checked: false },
    { value: "fish", label: "Fish", checked: false },
    { value: "flour", label: "Flour", checked: false },
    { value: "garlic", label: "Garlic", checked: false },
    { value: "green onions", label: "Green Onions", checked: false },
    { value: "green peppers", label: "Green Peppers", checked: false },
    { value: "ground beef", label: "Ground Beef", checked: false },
    { value: "honey", label: "Honey", checked: false },
    { value: "ketchup", label: "Ketchup", checked: false },
    { value: "lemons", label: "Lemons", checked: false },
    { value: "mayonnaise", label: "Mayonnaise", checked: false },
    { value: "mushrooms", label: "Mushrooms", checked: false },
    { value: "mustard", label: "Mustard", checked: false },
    { value: "onions", label: "Onions", checked: false },
    { value: "pasta", label: "Pasta", checked: false },
    { value: "peanut butter", label: "Peanut Butter", checked: false },
    { value: "pork chops", label: "Pork Chops", checked: false },
    { value: "potatoes", label: "Potatoes", checked: false },
    { value: "ramen", label: "Ramen", checked: false },
    { value: "rice", label: "Rice", checked: false },
    { value: "salsa", label: "Salsa", checked: false },
    { value: "sausage", label: "Sausage", checked: false },
    { value: "tomatoes", label: "Tomatoes", checked: false },
    { value: "tomato sauce", label: "Tomato Sauce", checked: false },
    { value: "tortillas", label: "Tortillas", checked: false },
    { value: "zucchini", label: "Zucchini", checked: false },
  ],
  selectedIngredients: [],
  recipes: [
    {
      id: 13934,
      title: "Fried Green Tomato Blt",
      image: "https://spoonacular.com/recipeImages/13934-312x231.jpg",
      imageType: "jpg",
      usedIngredientCount: 3,
      missedIngredientCount: 3,
      missedIngredients: [
        {
          id: 11250,
          amount: 1.0,
          unit: "piece",
          unitLong: "",
          unitShort: "",
          aisle: "Produce",
          name: "butter lettuce",
          original: "1 piece butter lettuce or watercress",
          originalString: "1 piece butter lettuce or watercress",
          originalName: "butter lettuce or watercress",
          metaInformation: [],
          meta: [],
          image:
            "https://spoonacular.com/cdn/ingredients_100x100/Butter-or-Boston-Bibb-lettuce.jpg",
        },
        {
          id: 4025,
          amount: 2.0,
          unit: "servings",
          unitLong: "servings",
          unitShort: "servings",
          aisle: "Condiments",
          name: "mayo",
          original: "mayo (homemade, if you are so inclined) or pesto",
          originalString: "mayo (homemade, if you are so inclined) or pesto",
          originalName: "mayo (homemade, if you are so inclined) or pesto",
          metaInformation: ["homemade", "(, if you are so inclined)"],
          meta: ["homemade", "(, if you are so inclined)"],
          image:
            "https://spoonacular.com/cdn/ingredients_100x100/mayonnaise.png",
        },
        {
          id: 11529,
          amount: 1.0,
          unit: "slice",
          unitLong: "slice",
          unitShort: "slice",
          aisle: "Produce",
          name: "tomato",
          original: "1 slice fried green tomato",
          originalString: "1 slice fried green tomato",
          originalName: "fried green tomato",
          metaInformation: ["green"],
          meta: ["green"],
          extendedName: "green tomato",
          image: "https://spoonacular.com/cdn/ingredients_100x100/tomato.png",
        },
      ],
      usedIngredients: [
        {
          id: 9037,
          amount: 3.0,
          unit: "",
          unitLong: "",
          unitShort: "",
          aisle: "Produce",
          name: "avocado",
          original: "3 slivers avocado",
          originalString: "3 slivers avocado",
          originalName: "slivers avocado",
          metaInformation: [],
          meta: [],
          image: "https://spoonacular.com/cdn/ingredients_100x100/avocado.jpg",
        },
        {
          id: 10123,
          amount: 2.0,
          unit: "slices",
          unitLong: "slices",
          unitShort: "slice",
          aisle: "Meat",
          name: "bacon",
          original: "2 slices bacon",
          originalString: "2 slices bacon",
          originalName: "bacon",
          metaInformation: [],
          meta: [],
          image:
            "https://spoonacular.com/cdn/ingredients_100x100/raw-bacon.png",
        },
        {
          id: 1059003,
          amount: 2.0,
          unit: "slices",
          unitLong: "slices",
          unitShort: "slice",
          aisle: "Produce",
          name: "red delicious apple",
          original:
            "2 slices of your favorite bread: levain or pain de mie would be delicious (I used Pamela",
          originalString:
            "2 slices of your favorite bread: levain or pain de mie would be delicious (I used Pamela",
          originalName:
            "your favorite bread: levain or pain de mie would be delicious (I used Pamela",
          metaInformation: ["your favorite"],
          meta: ["your favorite"],
          image:
            "https://spoonacular.com/cdn/ingredients_100x100/red-delicious-apples.png",
        },
      ],
      unusedIngredients: [
        {
          id: 9003,
          amount: 1.0,
          unit: "serving",
          unitLong: "serving",
          unitShort: "serving",
          aisle: "Produce",
          name: "apples",
          original: "apples",
          originalString: "apples",
          originalName: "apples",
          metaInformation: [],
          meta: [],
          image: "https://spoonacular.com/cdn/ingredients_100x100/apple.jpg",
        },
      ],
      likes: 0,
    },
  ],
  recipeInfo: [
    {
      vegetarian: false,
      vegan: false,
      glutenFree: true,
      dairyFree: true,
      veryHealthy: false,
      cheap: false,
      veryPopular: true,
      sustainable: false,
      weightWatcherSmartPoints: 20,
      gaps: "no",
      lowFodmap: false,
      aggregateLikes: 7815,
      spoonacularScore: 58.0,
      healthScore: 5.0,
      creditsText: "Oh Sweet Basil",
      sourceName: "Oh Sweet Basil",
      pricePerServing: 145.5,
      extendedIngredients: [
        {
          id: 9037,
          aisle: "Produce",
          image: "avocado.jpg",
          consistency: "solid",
          name: "avocado",
          original: "1 Avocado",
          originalString: "1 Avocado",
          originalName: "Avocado",
          amount: 1.0,
          unit: "",
          meta: [],
          metaInformation: [],
          measures: {
            us: {
              amount: 1.0,
              unitShort: "",
              unitLong: "",
            },
            metric: {
              amount: 1.0,
              unitShort: "",
              unitLong: "",
            },
          },
        },
        {
          id: 10123,
          aisle: "Meat",
          image: "raw-bacon.png",
          consistency: "solid",
          name: "bacon",
          original: "4-6 Strips of Bacon",
          originalString: "4-6 Strips of Bacon",
          originalName: "Bacon",
          amount: 4.0,
          unit: "Strips",
          meta: [],
          metaInformation: [],
          measures: {
            us: {
              amount: 4.0,
              unitShort: "Strips",
              unitLong: "Strips",
            },
            metric: {
              amount: 4.0,
              unitShort: "Strips",
              unitLong: "Strips",
            },
          },
        },
        {
          id: 19334,
          aisle: "Baking",
          image: "dark-brown-sugar.png",
          consistency: "solid",
          name: "brown sugar",
          original: "1/3 cup Brown Sugar",
          originalString: "1/3 cup Brown Sugar",
          originalName: "Brown Sugar",
          amount: 0.3333333333333333,
          unit: "cup",
          meta: [],
          metaInformation: [],
          measures: {
            us: {
              amount: 0.333,
              unitShort: "cups",
              unitLong: "cups",
            },
            metric: {
              amount: 78.863,
              unitShort: "ml",
              unitLong: "milliliters",
            },
          },
        },
        {
          id: 2009,
          aisle: "Spices and Seasonings",
          image: "chili-powder.jpg",
          consistency: "solid",
          name: "chili powder",
          original: "1/2-1 Teaspoon Chili Powder",
          originalString: "1/2-1 Teaspoon Chili Powder",
          originalName: "Chili Powder",
          amount: 0.5,
          unit: "Teaspoon",
          meta: [],
          metaInformation: [],
          measures: {
            us: {
              amount: 0.5,
              unitShort: "tsps",
              unitLong: "teaspoons",
            },
            metric: {
              amount: 0.5,
              unitShort: "tsps",
              unitLong: "teaspoons",
            },
          },
        },
      ],
      id: 674608,
      title: "Bacon Wrapped Avocados",
      readyInMinutes: 45,
      servings: 2,
      sourceUrl:
        "http://www.ohsweetbasil.com/bacon-wrapped-avocado-appetizer.html",
      image: "https://spoonacular.com/recipeImages/674608-556x370.jpg",
      imageType: "jpg",
      summary:
        'Bacon Wrapped Avocados is a <b>gluten free and dairy free</b> side dish. One serving contains <b>485 calories</b>, <b>8g of protein</b>, and <b>32g of fat</b>. For <b>$1.46 per serving</b>, this recipe <b>covers 12%</b> of your daily requirements of vitamins and minerals. If you have chili powder, bacon, brown sugar, and a few other ingredients on hand, you can make it. 7815 people have tried and liked this recipe. From preparation to the plate, this recipe takes about <b>45 minutes</b>. All things considered, we decided this recipe <b>deserves a spoonacular score of 62%</b>. This score is good. Try <a href="https://spoonacular.com/recipes/bacon-stuffed-avocados-21328">Bacon Stuffed Avocados</a>, <a href="https://spoonacular.com/recipes/avocados-with-warm-bacon-parsley-vinaigrette-101937">Avocados with Warm Bacon Parsley Vinaigrette</a>, and <a href="https://spoonacular.com/recipes/bacon-avocado-and-corn-salad-by-gaby-dalkins-absolutely-avocados-249433">Bacon, Avocado and Corn Salad by Gaby Dalkin’s “Absolutely Avocados”</a> for similar recipes.',
      cuisines: [],
      dishTypes: ["side dish"],
      diets: ["gluten free", "dairy free"],
      occasions: [],
      winePairing: {},
      instructions:
        'Heat the oven to 425In a small bowl, mix together the brown sugar and chili powder. Set asideLine a baking sheet with tin foil.Cut open the avocado and remove the pit. Slice about 3/4" slices lengthwise through the avocado, and then cut through the middle to cut all of the slices in half so that you have thick chunks of avocado.Cut each slice of bacon in 3-5 pieces and wrap each piece around the avocado. Roll in the brown sugar mixture and place on the baking sheet.Bake at 425 for 10-15 minutes. Remove from the oven to a platter and stick a tooth pick in each for serving.',
      analyzedInstructions: [
        {
          name: "",
          steps: [
            {
              number: 1,
              step:
                "Heat the oven to 425In a small bowl, mix together the brown sugar and chili powder. Set aside",
              ingredients: [
                {
                  id: 2009,
                  name: "chili powder",
                  localizedName: "chili powder",
                  image: "chili-powder.jpg",
                },
                {
                  id: 19334,
                  name: "brown sugar",
                  localizedName: "brown sugar",
                  image: "dark-brown-sugar.png",
                },
              ],
              equipment: [
                {
                  id: 404783,
                  name: "bowl",
                  localizedName: "bowl",
                  image: "bowl.jpg",
                },
                {
                  id: 404784,
                  name: "oven",
                  localizedName: "oven",
                  image: "oven.jpg",
                },
              ],
            },
            {
              number: 2,
              step: "Line a baking sheet with tin foil.",
              ingredients: [],
              equipment: [
                {
                  id: 404727,
                  name: "baking sheet",
                  localizedName: "baking sheet",
                  image: "baking-sheet.jpg",
                },
                {
                  id: 404765,
                  name: "aluminum foil",
                  localizedName: "aluminum foil",
                  image: "aluminum-foil.png",
                },
              ],
            },
            {
              number: 3,
              step:
                'Cut open the avocado and remove the pit. Slice about 3/4" slices lengthwise through the avocado, and then cut through the middle to cut all of the slices in half so that you have thick chunks of avocado.',
              ingredients: [
                {
                  id: 9037,
                  name: "avocado",
                  localizedName: "avocado",
                  image: "avocado.jpg",
                },
              ],
              equipment: [],
            },
            {
              number: 4,
              step:
                "Cut each slice of bacon in 3-5 pieces and wrap each piece around the avocado.",
              ingredients: [
                {
                  id: 9037,
                  name: "avocado",
                  localizedName: "avocado",
                  image: "avocado.jpg",
                },
                {
                  id: 10123,
                  name: "bacon",
                  localizedName: "bacon",
                  image: "raw-bacon.png",
                },
                {
                  id: 10018364,
                  name: "wrap",
                  localizedName: "wrap",
                  image: "flour-tortilla.jpg",
                },
              ],
              equipment: [],
            },
            {
              number: 5,
              step:
                "Roll in the brown sugar mixture and place on the baking sheet.",
              ingredients: [
                {
                  id: 19334,
                  name: "brown sugar",
                  localizedName: "brown sugar",
                  image: "dark-brown-sugar.png",
                },
                {
                  id: 0,
                  name: "roll",
                  localizedName: "roll",
                  image: "dinner-yeast-rolls.jpg",
                },
              ],
              equipment: [
                {
                  id: 404727,
                  name: "baking sheet",
                  localizedName: "baking sheet",
                  image: "baking-sheet.jpg",
                },
              ],
            },
            {
              number: 6,
              step: "Bake at 425 for 10-15 minutes.",
              ingredients: [],
              equipment: [
                {
                  id: 404784,
                  name: "oven",
                  localizedName: "oven",
                  image: "oven.jpg",
                },
              ],
              length: {
                number: 15,
                unit: "minutes",
              },
            },
            {
              number: 7,
              step:
                "Remove from the oven to a platter and stick a tooth pick in each for serving.",
              ingredients: [],
              equipment: [
                {
                  id: 404784,
                  name: "oven",
                  localizedName: "oven",
                  image: "oven.jpg",
                },
              ],
            },
          ],
        },
      ],
      originalId: null,
    },
    {
      vegetarian: false,
      vegan: false,
      glutenFree: true,
      dairyFree: true,
      veryHealthy: false,
      cheap: false,
      veryPopular: true,
      sustainable: false,
      weightWatcherSmartPoints: 5,
      gaps: "no",
      lowFodmap: false,
      preparationMinutes: 5,
      cookingMinutes: 15,
      aggregateLikes: 1207,
      spoonacularScore: 20.0,
      healthScore: 1.0,
      creditsText: "Oh Sweet Basil",
      sourceName: "Oh Sweet Basil",
      pricePerServing: 36.38,
      extendedIngredients: [
        {
          id: 9037,
          aisle: "Produce",
          image: "avocado.jpg",
          consistency: "solid",
          name: "avocado",
          original: "1 Avocado",
          originalString: "1 Avocado",
          originalName: "Avocado",
          amount: 1.0,
          unit: "",
          meta: [],
          metaInformation: [],
          measures: {
            us: {
              amount: 1.0,
              unitShort: "",
              unitLong: "",
            },
            metric: {
              amount: 1.0,
              unitShort: "",
              unitLong: "",
            },
          },
        },
        {
          id: 10123,
          aisle: "Meat",
          image: "raw-bacon.png",
          consistency: "solid",
          name: "bacon",
          original: "4-6 Strips of Bacon",
          originalString: "4-6 Strips of Bacon",
          originalName: "Bacon",
          amount: 4.0,
          unit: "Strips",
          meta: [],
          metaInformation: [],
          measures: {
            us: {
              amount: 4.0,
              unitShort: "Strips",
              unitLong: "Strips",
            },
            metric: {
              amount: 4.0,
              unitShort: "Strips",
              unitLong: "Strips",
            },
          },
        },
        {
          id: 19334,
          aisle: "Baking",
          image: "dark-brown-sugar.png",
          consistency: "solid",
          name: "brown sugar",
          original: "1/3 cup Brown Sugar",
          originalString: "1/3 cup Brown Sugar",
          originalName: "Brown Sugar",
          amount: 0.3333333333333333,
          unit: "cup",
          meta: [],
          metaInformation: [],
          measures: {
            us: {
              amount: 0.333,
              unitShort: "cups",
              unitLong: "cups",
            },
            metric: {
              amount: 78.863,
              unitShort: "ml",
              unitLong: "milliliters",
            },
          },
        },
        {
          id: 2009,
          aisle: "Spices and Seasonings",
          image: "chili-powder.jpg",
          consistency: "solid",
          name: "chili powder",
          original: "1/2-1 Teaspoon Chili Powder",
          originalString: "1/2-1 Teaspoon Chili Powder",
          originalName: "Chili Powder",
          amount: 0.5,
          unit: "Teaspoon",
          meta: [],
          metaInformation: [],
          measures: {
            us: {
              amount: 0.5,
              unitShort: "tsps",
              unitLong: "teaspoons",
            },
            metric: {
              amount: 0.5,
              unitShort: "tsps",
              unitLong: "teaspoons",
            },
          },
        },
      ],
      id: 1002215,
      title: "Bacon Wrapped Avocados",
      readyInMinutes: 20,
      servings: 8,
      sourceUrl: "https://ohsweetbasil.com/bacon-wrapped-avocado-appetizer/",
      image: "https://spoonacular.com/recipeImages/1002215-556x370.jpg",
      imageType: "jpg",
      summary:
        'Bacon Wrapped Avocados could be just the <b>gluten free and dairy free</b> recipe you\'ve been looking for. This recipe makes 8 servings with <b>121 calories</b>, <b>2g of protein</b>, and <b>8g of fat</b> each. For <b>36 cents per serving</b>, this recipe <b>covers 3%</b> of your daily requirements of vitamins and minerals. 1207 people were impressed by this recipe. It works well as a side dish. Head to the store and pick up bacon, avocado, chili powder, and a few other things to make it today. From preparation to the plate, this recipe takes approximately <b>20 minutes</b>. It is brought to you by Oh Sweet Basil. All things considered, we decided this recipe <b>deserves a spoonacular score of 50%</b>. This score is solid. If you like this recipe, take a look at these similar recipes: <a href="https://spoonacular.com/recipes/bacon-wrapped-avocados-674608">Bacon Wrapped Avocados</a>, <a href="https://spoonacular.com/recipes/bacon-stuffed-avocados-21328">Bacon Stuffed Avocados</a>, and <a href="https://spoonacular.com/recipes/avocados-with-warm-bacon-parsley-vinaigrette-101937">Avocados with Warm Bacon Parsley Vinaigrette</a>.',
      cuisines: [],
      dishTypes: ["side dish"],
      diets: ["gluten free", "dairy free"],
      occasions: [],
      winePairing: {},
      instructions:
        "Heat the oven to 425\nIn a small bowl, mix together the brown sugar and chili powder.\nSet aside\nLine a baking sheet with tin foil.\nCut open the avocado and remove the pit.\nSlice about 3/4 slices lengthwise through the avocado, and then cut through the middle to cut all of the slices in half so that you have thick chunks of avocado.\nCut each slice of bacon in 3-5 pieces and wrap each piece around the avocado.\nRoll in the brown sugar mixture and place on the baking sheet.\nBake at 425 for 10-15 minutes.\nRemove from the oven to a platter and stick a tooth pick in each for serving.",
      analyzedInstructions: [
        {
          name: "",
          steps: [
            {
              number: 1,
              step: "Heat the oven to 425",
              ingredients: [],
              equipment: [
                {
                  id: 404784,
                  name: "oven",
                  localizedName: "oven",
                  image: "oven.jpg",
                },
              ],
            },
            {
              number: 2,
              step:
                "In a small bowl, mix together the brown sugar and chili powder.",
              ingredients: [
                {
                  id: 2009,
                  name: "chili powder",
                  localizedName: "chili powder",
                  image: "chili-powder.jpg",
                },
                {
                  id: 19334,
                  name: "brown sugar",
                  localizedName: "brown sugar",
                  image: "dark-brown-sugar.png",
                },
              ],
              equipment: [
                {
                  id: 404783,
                  name: "bowl",
                  localizedName: "bowl",
                  image: "bowl.jpg",
                },
              ],
            },
            {
              number: 3,
              step: "Set aside",
              ingredients: [],
              equipment: [],
            },
            {
              number: 4,
              step: "Line a baking sheet with tin foil.",
              ingredients: [],
              equipment: [
                {
                  id: 404727,
                  name: "baking sheet",
                  localizedName: "baking sheet",
                  image: "baking-sheet.jpg",
                },
                {
                  id: 404765,
                  name: "aluminum foil",
                  localizedName: "aluminum foil",
                  image: "aluminum-foil.png",
                },
              ],
            },
            {
              number: 5,
              step: "Cut open the avocado and remove the pit.",
              ingredients: [
                {
                  id: 9037,
                  name: "avocado",
                  localizedName: "avocado",
                  image: "avocado.jpg",
                },
              ],
              equipment: [],
            },
            {
              number: 6,
              step:
                "Slice about 3/4 slices lengthwise through the avocado, and then cut through the middle to cut all of the slices in half so that you have thick chunks of avocado.",
              ingredients: [
                {
                  id: 9037,
                  name: "avocado",
                  localizedName: "avocado",
                  image: "avocado.jpg",
                },
              ],
              equipment: [],
            },
            {
              number: 7,
              step:
                "Cut each slice of bacon in 3-5 pieces and wrap each piece around the avocado.",
              ingredients: [
                {
                  id: 9037,
                  name: "avocado",
                  localizedName: "avocado",
                  image: "avocado.jpg",
                },
                {
                  id: 10123,
                  name: "bacon",
                  localizedName: "bacon",
                  image: "raw-bacon.png",
                },
                {
                  id: 10018364,
                  name: "wrap",
                  localizedName: "wrap",
                  image: "flour-tortilla.jpg",
                },
              ],
              equipment: [],
            },
            {
              number: 8,
              step:
                "Roll in the brown sugar mixture and place on the baking sheet.",
              ingredients: [
                {
                  id: 19334,
                  name: "brown sugar",
                  localizedName: "brown sugar",
                  image: "dark-brown-sugar.png",
                },
                {
                  id: 0,
                  name: "roll",
                  localizedName: "roll",
                  image: "dinner-yeast-rolls.jpg",
                },
              ],
              equipment: [
                {
                  id: 404727,
                  name: "baking sheet",
                  localizedName: "baking sheet",
                  image: "baking-sheet.jpg",
                },
              ],
            },
            {
              number: 9,
              step: "Bake at 425 for 10-15 minutes.",
              ingredients: [],
              equipment: [
                {
                  id: 404784,
                  name: "oven",
                  localizedName: "oven",
                  image: "oven.jpg",
                },
              ],
              length: {
                number: 15,
                unit: "minutes",
              },
            },
            {
              number: 10,
              step:
                "Remove from the oven to a platter and stick a tooth pick in each for serving.",
              ingredients: [],
              equipment: [
                {
                  id: 404784,
                  name: "oven",
                  localizedName: "oven",
                  image: "oven.jpg",
                },
              ],
            },
          ],
        },
      ],
      originalId: null,
    },
  ],
  user: [],
  username: "testuser",
  userRecipes: [
    {
      id: 14,
      recipeid: 620313,
      title: "Cheddar Apple Bacon Grilled Cheese",
      image: "https://spoonacular.com/recipeImages/620313-312x231.jpg",
      url:
        "http://www.emilybites.com/2014/11/cheddar-apple-bacon-grilled-cheese.html",
      userid: 4,
    },
    {
      id: 15,
      recipeid: 599414,
      title: "Cheddar, Bacon and Apple Grilled Cheese Sandwich",
      image: "https://spoonacular.com/recipeImages/599414-312x231.jpg",
      url:
        "http://leitesculinaria.com/87793/recipes-cheddar-bacon-grilled-cheese-sandwich.html",
      userid: 4,
    },
    {
      id: 16,
      recipeid: 270911,
      title: "Cheesy Apple-Cinnamon Raisin Grill",
      image: "https://spoonacular.com/recipeImages/270911-312x231.jpg",
      url:
        "http://www.Kraftrecipes.com/recipes/cheesy-apple-cinnamon-raisin-grill-56990.aspx",
      userid: 4,
    },
    {
      id: 17,
      recipeid: 244967,
      title: "Spicy Honey Mustard Dipping Sauce",
      image: "https://spoonacular.com/recipeImages/244967-312x231.jpg",
      url:
        "http://www.deepsouthdish.com/2011/04/spicy-honey-mustard-dipping-sauce.html",
      userid: 4,
    },
    {
      id: 19,
      recipeid: 83669,
      title: "Yo Ho! Let's Go! Bacon Roll-Up",
      image: "https://spoonacular.com/recipeImages/83669-312x231.jpg",
      url: "http://www.kraftrecipes.com/recipes/yo-ho-lets-go-50151.aspx",
      userid: 4,
    },
  ],
  loading: false,
  setLoadingToTrue: (e) => {},
  setLoadingToFalse: () => {},
  getUsername: (username) => {},
  clearUsername: () => {},
  toggleChecked: (index) => {},
  getRecipes: () => {},
  getRecipesByUserId: () => {},
  saveRecipe: (e, recipe, id) => {},
  deleteSavedRecipe: (e, recipe) => {},
});
